use analytics_practice;
show tables;
select * from sales;
select order_id,product,revenue from sales;
select region,salesperson,product from sales;
select distinct region from sales;
SELECT DISTINCT product FROM sales;
SELECT DISTINCT salesperson FROM sales;
SELECT * FROM sales WHERE region = "Kathmandu";
SELECT * FROM sales WHERE salesperson ="Priya";
SELECT * FROM sales WHERE product ="Laptop";
SELECT * FROM sales WHERE revenue > 100000;
SELECT * FROM sales WHERE revenue < 50000;
SELECT * FROM sales WHERE units >= 10;
SELECT * FROM sales WHERE units <=5;
SELECT * FROM sales WHERE region <> "Kathmandu";
SELECT order_id, region,product, revenue FROM sales WHERE revenue > 100000;
SELECT order_id, region, salesperson, units, revenue FROM sales WHERE product = "Laptop";
SELECT order_id, region,product,revenue FROM sales WHERE region != "Kathmandu";
SELECT order_id, product, units, revenue FROM sales WHERE units <= 5;
SELECT * FROM sales WHERE revenue >= 100000 AND product = "Monitor";
SELECT DISTINCT region FROM sales;
SELECT DISTINCT product FROM sales;
SELECT order_id, salesperson, product, units, revenue FROM sales WHERE region ="Kathmandu" AND revenue > 100000;