USE analytics_practice;
SELECT * FROM sales;
SELECT order_id, product, revenue FROM sales ORDER BY revenue DESC limit 5;
SELECT order_id, product, revenue FROM sales ORDER BY revenue ASC LIMIT 3;
SELECT * FROM sales ORDER BY units DESC LIMIT 5;
SELECT * FROM sales WHERE region = "Kathmandu" Order By revenue DESC limit 1;
SELECT * FROM sales WHERE region = "Kathmandu" Order By revenue DESC limit 3;
SELECT * FROM sales ORDER BY revenue DESC;
SELECT * FROM sales ORDER BY revenue ASC;
SELECT * FROM sales ORDER BY units DESC;
SELECT * FROM sales ORDER BY revenue DESC LIMIT 5;
SELECT * FROM sales ORDER BY revenue ASC LIMIT 5;
SELECT * FROM sales ORDER BY units DESC LIMIT 3;
SELECT * FROM sales WHERE region ="Kathmandu" ORDER BY revenue DESC;
SELECT * FROM sales WHERE region ="Kathmandu" ORDER BY revenue DESC LIMIT 3;
SELECT * FROM sales WHERE product ="laptop" ORDER BY revenue DESC;
SELECT * FROM sales WHERE product ="laptop" ORDER BY revenue DESC LIMIT 2;
SELECT order_id, product, salesperson, region, revenue FROM sales ORDER BY revenue DESC LIMIT 5;
SELECT order_id, product, salesperson, revenue FROM sales WHERE region ="Lalitpur" ORDER BY revenue DESC LIMIT 3;
SELECT order_id, region, product, units FROM sales ORDER BY units DESC LIMIT 5;
SELECT order_id, region, salesperson, units, revenue FROM sales WHERE product ="laptop" ORDER BY revenue DESC LIMIT 5;
SELECT order_id, product, revenue FROM sales WHERE revenue > 50000 ORDER BY revenue DESC;
SELECT order_id, region, salesperson, product, revenue FROM sales ORDER BY revenue DESC LIMIT 1;
SELECT order_id, product, revenue FROM sales WHERE region = "Kathmandu" ORDER BY revenue ASC LIMIT 1;
SELECT order_id, region, salesperson, product, units, revenue FROM sales WHERE category ="Electronics" ORDER BY revenue DESC LIMIT 5;